import { build } from 'esbuild';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const directory = path.dirname(fileURLToPath(import.meta.url));
const output = path.resolve(directory, '../../web/vendor');
const result = await build({
  absWorkingDir: directory,
  entryPoints: ['entry.js'],
  bundle: true,
  minify: true,
  format: 'iife',
  globalName: 'CM',
  legalComments: 'none',
  metafile: true,
  write: false,
});

// Include notices for the packages actually included in the bundle.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  const match = input.match(/^node_modules\/((?:@[^/]+\/)?[^/]+)/);
  if (!match || packages.has(match[1])) continue;
  const root = path.join(directory, 'node_modules', match[1]);
  const metadata = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
  const licenses = (await readdir(root)).filter(name => /^(license|copying|notice)(\.|$)/i.test(name)).sort();
  if (!licenses.length) throw new Error(`Missing license text for ${metadata.name}`);
  const texts = await Promise.all(licenses.map(name => readFile(path.join(root, name), 'utf8')));
  packages.set(metadata.name, `${metadata.name} ${metadata.version}\n${texts.join('\n').trim()}\n`);
}
const notices = 'Third-party notices for codemirror.js\nGenerated by tools/codemirror/build.mjs.\n\n'
  + [...packages].sort(([a], [b]) => a.localeCompare(b, 'en')).map(([, text]) => text).join('\n' + '='.repeat(72) + '\n\n');
const files = new Map([
  ['codemirror.js', result.outputFiles[0].text],
  ['LICENSE-codemirror', notices],
]);
for (const [name, content] of files) {
  const destination = path.join(output, name);
  if (process.argv.includes('--check')) {
    if (await readFile(destination, 'utf8') !== content) throw new Error(`${name} is out of date; run npm run build`);
  } else {
    await writeFile(destination, content);
  }
}
console.log(`${process.argv.includes('--check') ? 'Checked' : 'Built'} CodeMirror and notices for ${packages.size} packages`);
